server:
  request_timeout: 4000ms
  shutdown_timeout: 4000ms
  port: 8081
httpclient:
  response_header_timeout: 10000ms
  tls_handshake_timeout: 10000ms
  idle_conn_timeout: 10000ms
  dial_timeout: 10000ms
log:
  level: debug
  format: kibana
storage:
  uri: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
  encryption_key: ejHjRNHbS0NaqARSRvnweVV9zcmhQEa8
#storage:
#  name: sm-postgres
health:
  indicators:
    storage:
      fatal: true
      failures_threshold: 3
      interval: 30s
    platforms:
      fatal: true
      failures_threshold: 3
      interval: 30s
api:
  token_issuer_url: http://localhost:8080
  skip_ssl_validation: false
  resp_header_blacklist: Set-Cookie
authz:
  client_id: sm_admin
  trusted_client_id_suffix: "|clone"
  scope_space: "sm"
  master_app_id: "master"
  xsuaa_url: http://localhost:8080
authn:
  tenant_ids: localhost
cis:
  url: http://localhost:8082
  context_api_prefix: /provisioning/v1/subaccountContext/
  lem_url: http://localhost:8082
  lem_api_prefix: /entitlements/v1/
  auth:
    client_id: sm_admin
    client_secret: 1234d
    token_endpoint: http://localhost:8080/oauth/token
