language: go

go:
  - 1.12.x

addons:
  postgresql: "9.6"

install:
  - make prepare

services:
  - postgresql

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - make unit-test-precommit
        - goveralls -coverprofile profile.cov -service=travis-ci
        - kill %1
    - stage: "Tests"
      name: "Integration Tests"
      script:
        - make integration-test-precommit
        - goveralls -coverprofile profile.cov -service=travis-ci
        - kill %1
    - stage: "Tests"
      name: "Resources Integration Tests"
      script:
        - make resources-test-precommit
        - goveralls -coverprofile profile.cov -service=travis-ci
        - kill %1

env:
  - COVERALLS_PARALLEL=true

notifications:
  slack: openservicebrokerapi:KQo2QAC6LXeEeXPOemOXja48
