language: go

go:
  - 1.12.x

addons:
  postgresql: "9.6"

install:
  - make prepare

services:
  - postgresql

script:
  - travis_wait 30 make precommit
  - goveralls -coverprofile profile.cov -service=travis-ci


notifications:
  slack: openservicebrokerapi:KQo2QAC6LXeEeXPOemOXja48
