language: go

go:
  - 1.11.x

install:
  - make prepare

services:
  - postgresql

script:
  - travis_wait make precommit
  - goveralls -coverprofile profile.cov -service=travis-ci

notifications:
  slack: openservicebrokerapi:KQo2QAC6LXeEeXPOemOXja48
