server:
  request_timeout: 4000000ms
  shutdown_timeout: 4000000ms
  port: 8081
  # max_body_bytes: 4000
  # max_header_bytes: 1000
httpclient:
  response_header_timeout: 1000000ms
  tls_handshake_timeout: 1000000ms
  idle_conn_timeout: 1000000ms
  dial_timeout: 1000000ms
  skip_ssl_validation: false
websocket:
  ping_timeout: 6000ms
  write_timeout: 6000ms
log:
  level: debug
  format: text
storage:
  #  name: sm-postgres
  uri: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
  encryption_key: ejHjRNHbS0NaqARSRvnweVV9zcmhQEa8
  skip_ssl_validation: false
  max_idle_connections: 5
api:
  token_issuer_url: http://localhost:8080
  client_id: admin-client
operations:
  cleanup_interval: 30m
  job_timeout: 12m
  scheduled_deletion_timeout: 12h
  polling_interval: 5s
  rescheduling_interval: 5s
  pools:
    - resource: service_broker
      size: 100
    - resource: platform
      size: 10
    - resource: visibility
      size: 25
multitenancy:
  label_key: tenant
